FROM cp.icr.io/cp/appc/ace-server-prod@sha256:dd1f5112da3b86250efdf66400b29e2fa66a5499bf22068efb2721282513c12d
COPY Customer /home/aceuser/Customer
RUN export LICENSE="accept" \
    && source /opt/ibm/ace-11/server/bin/mqsiprofile \
    && mkdir /home/aceuser/bars \
    && mqsipackagebar -a bars/FE.bar -k Customer \
    && mqsibar -a bars/FE.bar -w /home/aceuser/ace-server \
    && chmod -R 777 /home/aceuser/ace-server/run/Customer
